services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: filesync
      POSTGRES_PASSWORD: filesync_dev
      POSTGRES_DB: filesync_dev
    volumes:
      - postgres_local_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U filesync -d filesync_dev"]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "5432:5432"

volumes:
  postgres_local_data:
